### ISSUE TITLE
Is there any way to disable audio access?

### ISSUE THREAD

**Issue by Moonif** [PlayFab/PlayFabPartyUnity#10]
Hello,

I'm using PlayFab Party for a turn-based game, but I don't want to use the voice chat function, and I really don't want the game to ask for permission to use the user's microphone either.
Is there anything I can do to disable the voice chat feature completely?

Thank you!

**Comment by MichaelTGood** [comment]
I'd like to second this question. I hadn't even implemented any chat messaging yet when building the demo scene to iPhone, and I was surprised to find Xcode insisting I add a description for microphone use. 

I just need data and chat (text) messages, and I'd like to limit the amount of asked permissions. Thanks!

**Comment by iequalshane** [comment]
Not that I could find. I removed it from the PlayFabMultiplayerManager code for my own game which didn't need chat communication.

**Comment by wtblife** [comment]
> Not that I could find. I removed it from the PlayFabMultiplayerManager code for my own game which didn't need chat communication.

Can you explain in more detail what you did? I'm not having much luck getting rid of the requirement.

**Comment by outbrkgame** [comment]
> Not that I could find. I removed it from the PlayFabMultiplayerManager code for my own game which didn't need chat communication.

Hi @iequalshane , How did you manage to remove it? I am specifically looking to remove the voice part of it.

**Comment by nassosterz-ms** [comment]
Hello,

Is this issue still open? It just caught my attention. Currently, we ship the PlayFab Party Plugin on Unity with Voice Chat enabled by default. If voice chat is desired to be disabled, please comment out in src/Assets/PlayFabPartySDK/Source/Scripts/PartyUnitySDK/PlayFabMultiplayerManager.cs the call to SetUserSettings(); inside AuthenticateLocalUserComplete().

Let us know if this works.

**Comment by outbrkgame** [comment]
Hi Nassos,

That fixed it, thank you so much.

You can go ahead and close the ticket !

Cheers
