### ISSUE TITLE
Network interruption causes _playFabMultiplayerManagerState to be stuck in wrong state.

### ISSUE THREAD

**Issue by iequalshane** [PlayFab/PlayFabPartyUnity#24]
When PARTY_STATE_CHANGE_TYPE_NETWORK_DESTROYED is encountered and contains an errorDetail like 63 "failed to establish or maintain a connection to a network or remote peer", it does NOT set _playFabMultiplayerManagerState back to Initialized causing the state to be stuck in ConnectedToNetwork. Any attempts to join or create a network in the future will try to leave a network with a bad network handle because it's still in a ConnectedToNetwork without being connected to a network. PARTY_STATE_CHANGE_TYPE_NETWORK_DESTROYED should always result in the _playFabMultiplayerManagerState going back to the Initialized state regardless of error.

**Comment by goodspeed3** [comment]
Did you change any code to help solve this?  I tried manually setting _playFabMultiplayerManagerState back to Initialized but it's not letting me connect after network interruption, e.g., when I put the phone to sleep.

**Comment by iequalshane** [comment]
The only thing I added as part of my fix was setting the state back to initialized even if errorDetail is set. It's possible I've fixed something else earlier that helps this work better since my join flow is quite different from the normal code to allow for creating but not joining a network. I'd step through the JoinNetwork call and see where it fails.

`                            case PARTY_STATE_CHANGE_TYPE.PARTY_STATE_CHANGE_TYPE_NETWORK_DESTROYED:
                                {
                                    var stateChangeConverted = (PARTY_NETWORK_DESTROYED_STATE_CHANGE)stateChange;
                                    if (PartySucceeded(stateChangeConverted.errorDetail))
                                    {
                                        if (_queuedCreateAndJoinAfterLeaveNetworkOp.queued ||
                                            _queuedCompleteJoinAfterLeaveNetworkOp.queued)
                                        {
                                            if (_queuedCreateAndJoinAfterLeaveNetworkOp.queued)
                                            {
                                                _queuedCreateAndJoinAfterLeaveNetworkOp.queued = false;
                                                CreateAndJoinNetworkImplComplete(_queuedCreateAndJoinAfterLeaveNetworkOp.networkConfiguration);
                                            }
                                            if (_queuedCompleteJoinAfterLeaveNetworkOp.queued)
                                            {
                                                _queuedCompleteJoinAfterLeaveNetworkOp.queued = false;
                                                JoinNetworkImplComplete(_queuedCompleteJoinAfterLeaveNetworkOp.networkId);
                                            }
                                        }
                                        else
                                        {
                                            _playFabMultiplayerManagerState = _InternalPlayFabMultiplayerManagerState.Initialized;
                                        }
                                    }
                                    else
                                    {
                                        _playFabMultiplayerManagerState = _InternalPlayFabMultiplayerManagerState.Initialized;
                                    }
                                    break;
                                }`
