### ISSUE TITLE
Game crashes after Unity logo in android

### ISSUE THREAD

**Issue by karascr** [PlayFab/PlayFabPartyUnity#4]
Everything works fine on Unity editor and windows build. According to the codes on this page (https://docs.microsoft.com/en-us/gaming/playfab/features/multiplayer/networking/party-unity-plugin-quickstart). But when I try to build for android and run the game, it is crashing after the Unity logo disappears. I am new in Unity game developing, I could not be able to solve the problem. I tried adb logcat but I did not see any error or log messages about crash. When I build the app without "PlayFabMultiplayerManager" prefab, app does not crash. I tried creating brand new project and I have imported only necessary packages for PlayFab Unity Party, result is the same. Including "PlayFabMultiplayerManager" prefab in to the scene crashes game in android device. I have tried android studio emulator, bluestacks emulator and samsung a50 device but problem remains.
My unity verison is Unity 2019.4.3f1 Personal
Playfab editor and packages are up to date according today.
Android target Api version is 30.
I have checked "allow unsafe" option in player settings.
Android SDK & NDK Tools and OpenJDK are installed.

**Comment by Vicodex** [comment]
Hi karascr, 
Thanks for the detailed info about the issue. Just to clarify, is your PlayFab title enabled for Party feature (Title Settings --> Multiplayer --> Party tab in your PlayFab Development Dashboard portal (https://developer.playfab.com/))?

**Comment by karascr** [comment]
Yes, it is enabled. I have tested this api on windows builds. Everything was fine in windows build, I have tested voice and chat message successfully. But when I try to build and run same project in android, game crashed after Unity logo disappeared.

**Comment by Jorbyland** [comment]
Hi Vicodex,
I have exactly the same problem than karascr on Android.
In my log I can see a Null Ref Exp before the crash.
I'm on Unity 2019.3.15f1.
I have checked "allow unsafe" option in player settings but nothing to allow microphone.

**Comment by Vicodex** [comment]
Hi Jorbyland, thanks for letting us know. We are looking into this and will update this thread once we have some results. Stay tuned!

**Comment by Vicodex** [comment]
Unity package for pre-release `1.4.8.0-main.0` has been updated (please note new date marker `8.14.2020` in its name). Accidentally the previous content of the package did not include a necessary gradle file for Android in `Plugins/Android` directory. That has been fixed in updated package and should resolve the crash issue on Android app launch.

**Comment by karascr** [comment]
Thanks, game did not crash and messages recieved successfully.

**Comment by Jorbyland** [comment]
Nice job, thanks !!
