### ISSUE TITLE
libparty.so Android build sizes very large

### ISSUE THREAD

**Issue by Tythe** [PlayFab/PlayFabPartyUnity#43]
When building a clean project using Android App Bundles (.abb) and Split Application Binary with only the latest playfab party SDK (1.9.3.0), libparty.so takes up 86.3MB in the base module. With the playstore restricting the size of the base module to 200MB, libparty.so taking up close to 50% of the total budget seems excessive. Especially considering it's larger than the Unity Engine objects. 

Is there a way to reduce the size or have libparty included in an external module?

**Comment by nassosterz-ms** [comment]
Hello,

Apologies for the late response. We are looking into this, as we are already working on reducing the size of the produced libparty.so.

We should have an updated in the next 2 weeks.

Thanks,
Nassos

**Comment by nassosterz-ms** [comment]
Hello,

Please see our release here https://github.com/PlayFab/PlayFabParty/releases/tag/v1.10.0

In the Android zip, please find libparty-full-release.aar and use it in your Unity application. The size now is around 8 MB.

Again, we appreciate that you raised the issue. I am not sure on our timeline of releasing an updated package for Party Unity Android thus for now I recommend following the above process.

Let me know if you face any issues!

**Comment by nassosterz-ms** [comment]
Let me know if you face any issues! In the meantime, I am closing this issue

**Comment by Tythe** [comment]
Worked like a charm. Thanks for fixing the issue!
