### ISSUE TITLE
DllNotFoundException: PartyWin32

### ISSUE THREAD

**Issue by klfw** [PlayFab/PlayFabPartyUnity#5]
I see that version 1.4.8 includes a PartyWin32.dll, but I am still getting the same error.
DllNotFoundException: PartyWin32
PartyCSharpSDK.SDK.PartyInitialize (System.String titleId, PartyCSharpSDK.PARTY_HANDLE& handle) (at Assets/PlayFabPartySDK/Source/Scripts/PartySDKCSharpSource/SDK.cs:39)
PlayFab.Party.PlayFabMultiplayerManager._Initialize () (at Assets/PlayFabPartySDK/Source/Scripts/PartyUnitySDK/PlayFabMultiplayerManager.cs:632)
PlayFab.Party.PlayFabMultiplayerManager.Awake () (at Assets/PlayFabPartySDK/Source/Scripts/PartyUnitySDK/PlayFabMultiplayerManager.cs:125)

Has this support for Win32 been added?

**Comment by Vicodex** [comment]
Hi klfw,
[PlayFab Party Unity SDK 1.4.8.0-main.0](https://github.com/PlayFab/PlayFabPartyUnity/releases/tag/1.4.8.0-main.0) supports Win32 as a platform ("PC, Mac & Linux Standalone" item in Unity's Built Settings window). However, only `x86_64` CPU architecture is supported since the underlying Party binaries are 64-bit only on Win32.
If a different selected CPU architecture is not the reason of the issue, could you please kindly provide more information about your development environment: version of OS and Unity?

**Comment by klfw** [comment]
I am trying to build for Android but the error occurs regardless of the platform I choose in the build settings.
Unity is 2019.4.1f1 and Windows 7 6.1.7601

**Comment by JohnManna** [comment]
Experiencing the same issue trying to build to Windows 64 bit with IL2CPP.  There is no such DLL within the project, only PartyCSharpSDK.dll and PartyXBLCSharpSDK.dll.

**Comment by Vicodex** [comment]
To make sure we are on the same page here, could you guys please kindly give us some additional information:
1. Are you using `playfab-party.1.4.8.0-main.0-8.14.2020-preview.unitypackage`?
2. Do you have files `PartyWin32.dll` and `PartyXboxLiveWin32.dll` in subdirectory `\Assets\PlayFabPartySDK\Source\DLLs\Win32` of your project? They should be copied there when you import our Party Unity SDK package.
3, Do you have these files (`PartyWin32.dll` and `PartyXboxLiveWin32.dll`) in `\<ProjectName>_Data\Plugins\x86_64` subdirectory of your build output directory when you build your project for Windows?

**Comment by klfw** [comment]
1. yes
2. yes
3. yes

**Comment by Vicodex** [comment]
I am going to close this issue since the libraries PartyWin32.dll and PartyXboxLiveWin32.dll are in the right locations, and vast majority of other users don't experience this. You may also try to use the latest pre-release (1.5.0.1-main.0).
