### ISSUE TITLE
How do I get access to this?

### ISSUE THREAD

**Issue by RubberBandGames** [PlayFab/PlayFabPartyUnity#8]
Hi,

I'm working on PlayFabParty for Xbox One in Unity,
the documentation takes me to this github, however I do not see any packages, do I need to send a request to view this?
If so how do I do that?

Thanks

**Comment by Vicodex** [comment]
Hi RubberBandGames,
PlayFabParty Unity supports Xbox One only via Microsoft Game Core platform. You will need to get access to http://aka.ms/gdkdl first. PlayFabParty Unity package for GDK (Game Core SDK) is distributed as part of GDK, it is included in its Unity plugin that is installed with it. Here on GitHub you may access preview versions of Party Unity SDK for earlier versions of GDK, there are available as Unity packages in Releases section: https://github.com/PlayFab/PlayFabPartyUnity/releases

**Comment by matt-bcs** [comment]
Hi @Vicodex where can we find the package for 2020.06?  I'm not finding a Unity package in that installation folder.

**Comment by Vicodex** [comment]
For 2020.6 please use [PlayFabPartyUnity 1.4.8.0-main.0](https://github.com/PlayFab/PlayFabPartyUnity/releases/download/1.4.8.0-main.0/playfab-party.1.4.8.0-main.0-8.14.2020-preview.unitypackage). You will need to copy Party binaries from installed GDK (please follow instructions in PlayFabPartyUnity README).
